In [181]:
%load_ext autoreload
%autoreload 2 
from sys import path 
path.append('../')

import numpy as np 
import pandas as pd 
import edhec_risk_kit as erk

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [182]:
ind = erk.get_hfi_returns()
ind = ind['2000':]
er = erk.annualize_rets(ind['2000':], 12)
cov = ind['2000':].cov()

/home/tom/Dropbox/projects/coursera_edhec_AdvancedPortfolioConstructionAndAnalysisWithPython/Week 2-Section 2-Section 1-Introduction to Optimization and The Efficient Frontier/../edhec_risk_kit.py:22: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  hfi = pd.read_csv("../data/edhec-hedgefundindices.csv",


In [183]:
erk.var_gaussian(ind, level=1) * 100

Convertible Arbitrage      3.484471
CTA Global                 5.033613
Distressed Securities      3.143018
Emerging Markets           5.807041
Equity Market Neutral      1.477190
Event Driven               3.085309
Fixed Income Arbitrage     1.951918
Global Macro               2.461907
Long/Short Equity          3.942044
Merger Arbitrage           1.535518
Relative Value             2.160459
Short Selling             10.213030
Funds Of Funds             2.938540
dtype: float64

In [184]:
erk.var_gaussian(ind, level=1, modified=True) * 100

Convertible Arbitrage     10.366556
CTA Global                 4.664321
Distressed Securities      4.966909
Emerging Markets           8.679551
Equity Market Neutral      4.143206
Event Driven               4.573181
Fixed Income Arbitrage     6.647930
Global Macro               2.278564
Long/Short Equity          5.138116
Merger Arbitrage           2.128243
Relative Value             4.898484
Short Selling              9.832259
Funds Of Funds             4.879303
dtype: float64

In [185]:
erk.var_historic(ind, level=1) * 100

Convertible Arbitrage      3.1674
CTA Global                 5.0938
Distressed Securities      4.2642
Emerging Markets           6.5496
Equity Market Neutral      1.9800
Event Driven               3.8540
Fixed Income Arbitrage     3.0748
Global Macro               2.2632
Long/Short Equity          4.5060
Merger Arbitrage           2.2654
Relative Value             2.1788
Short Selling             10.7684
Funds Of Funds             2.7200
dtype: float64

In [186]:
ind = erk.get_ind_returns()
er = erk.annualize_rets(ind['2013':'2017'], 12)
cov = ind['2013':'2017'].cov()

In [187]:
l = ['Books', 'Steel', 'Oil', 'Mines']
rf_rate = 0.1

In [188]:
# equal return 
n = er[l].shape[0]
w_ew = np.repeat(1/n, n)
w_ew * 100

array([25., 25., 25., 25.])

In [189]:
# max sharpe ratio 
w_msr = erk.msr(riskfree_rate=rf_rate, er=er[l], cov=cov.loc[l,l])
w_msr * 100

array([0.00000000e+00, 1.00000000e+02, 6.00214323e-14, 7.35522754e-14])

In [190]:
w_gmv = erk.gmv(cov=cov.loc[l,l])
w_gmv * 100


array([4.77024865e+01, 4.33680869e-17, 4.34112030e+01, 8.88631048e+00])

In [191]:
erk.portfolio_vol(w_msr, ind['2018'][l].cov()) * (12**0.5) * 100

/tmp/ipykernel_13879/598143374.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  erk.portfolio_vol(w_msr, ind['2018'][l].cov()) * (12**0.5) * 100


21.9839881814842

In [192]:
erk.portfolio_vol(w_gmv, ind['2018'][l].cov()) * (12**0.5) * 100

/tmp/ipykernel_13879/4194746369.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  erk.portfolio_vol(w_gmv, ind['2018'][l].cov()) * (12**0.5) * 100


18.973734554913555